### ISSUE TITLE
background-color

### ISSUE THREAD

**Issue by strarsis** [gre/deprecated-kenburns-dom#3]
Why is a background-color set on the container div?
it is possible to force a different color (e.g. transparent), but it would be an unnecessary override.

This seems to be related with the clamped issue: https://github.com/gre/kenburns/issues/1

**Comment by gre** [comment]
that's a good point. I think it was mostly for consistence across implementations, but we should probably allow opacity there. so you should be able to set color=[0,0,0,0] (aka transparent) which should probably be the default.

**Comment by gre** [comment]
tomorrow i'll try to refactor the modules & merge into multiple files in kenburns (because it's pointless to split in so many repos)

**Comment by gre** [comment]
background-color feature is preserved but it's only important if you use `clamped: false`. by default `clamped` is true which ensures the image never goes out of bound (the background is the out of bounds part).

I'm seriously considering actually removing these 2 attributes, because I actually don't see why you would ever want to disable that clamp behavior.
